In [1]:
import numpy as np
import pandas as pd

In [2]:
source = pd.read_excel('data.xlsx',sheet_name='source')

In [3]:
df = pd.read_excel('data.xlsx',sheet_name='data')

In [4]:
source

                   محله  منطقه     شهر
0             حصاربوعلی       1  تهران
1    رستم آباد- فرمانیه       1  تهران
2                  اوین       1  تهران
3                  درکه       1  تهران
4              زعفرانیه       1  تهران
..                  ...     ...    ...
623          واریان شهر      10    کرج
624           کلاک بالا      11    کرج
625          کلاک پایین      11    کرج
626                حصار      11    کرج
627       شهرک جهان نما      11    کرج

[628 rows x 3 columns]

In [5]:
df

,Number,Customer Name,Details,Latitude,Longitude,Address L4,City Area
0,1081095,ابراهیم آل ابراهیم - سایت تهران - 2237760,خ محلاتی خ کیانی خ میثم انتهای خیابان پ 7,___,___,___,___
1,1117381,جواد بیگلری سایت کرج,فردیس کانال غربی خ دهکده بازار روز نقشه جهان غ...,35.733427,50.970085,___,___
2,1104462,شرکت زنجیره ای غذایی امیران (برغان),کرج-میدان آزادگان-خیابان برغان-رو به روی بازار...,35.8212,51.0018,___,___
3,1104474,شرکت زنجیره ای غذایی امیران (عظیمیه),کرج-عظیمیه – خیابان میخک بازار روز سابق میخک,35.8407,51.0099,___,___
4,1067853,فروشگاه اتکا فاز 4 مهرشهر-سایت کرج,کرج-فاز 4 مهرشهر- بلوار شهید خانزاده قبل از چه...,35.8138,50.9316,___,___
...,...,...,...,...,...,...,...
5997,1078592,وین مارکت کرشته1087 وین مارکت کرشته1087 - سایت...,شهریار خیابان مصطفی خمینی(کرشته)نبش کوچه پرویز...,___,___,___,___
5998,1079062,وین مارکت معلم (1062) - سایت تهران - 2252893,شهریار- میدان معلم-خیابان بهشتی شرقی- جنب هلال...,___,___,___,___
5999,1078676,وین مارکت ورامین 1089 وین مارکت ورامین 1089 - ...,ورامین بلوار معلم خیابان دولت بعد از کوچه اندی...,___,___,___,___
6000,1079033,ویوان باقر شهر فاتحی1030 - سایت تهران - 2253985,باقر شهر ، خیابان 22 بهمن ، نبش میدان فاتحی ، ...,35.5341,51.4058,___,___
6001,1079032,ویوان شهر قدس1029 - سایت تهران - 2253977,خیابان طالقانی ، روبروی کوچه بهداشت، پلاک 408,35.6724,51.3265,___,___